local display = false

RegisterCommand("nui", function(source, args)
    SetDisplay(not display)
end)

--very important cb 
RegisterNUICallback("close", function(data)
    SetDisplay(false)
end)

RegisterNUICallback("button1", function()
    SetTimecycleModifier('MP_Powerplay_blend')
    SetExtraTimecycleModifier('reflection_correct_ambient')
end)
RegisterNUICallback("button2", function() 
    SetTimecycleModifier('tunnel')
    ClearAllBrokenGlass()
    ClearAllHelpMessages()
    LeaderboardsReadClearAll()
    ClearBrief()
    ClearGpsFlags()
    ClearPrints()
    ClearSmallPrints()
    ClearReplayStats()
    LeaderboardsClearCacheData()
    ClearFocus()
    ClearHdArea()
    ClearPedBloodDamage(PlayerPedId())
    ClearPedWetness(PlayerPedId())
    ClearPedEnvDirt(PlayerPedId())
    ResetPedVisibleDamage(PlayerPedId())
    ClearOverrideWeather()
    ClearHdArea()
    DisableVehicleDistantlights(false)
    DisableScreenblurFade()
    SetRainLevel(0.0)
    SetWindSpeed(0.0)
    Citizen.Wait(300)
end)
RegisterNUICallback("button3", function()
    SetTimecycleModifier('yell_tunnel_nodirect')
    ClearAllBrokenGlass()
    ClearAllHelpMessages()
    LeaderboardsReadClearAll()
    ClearBrief()
    ClearGpsFlags()
    ClearPrints()
    ClearSmallPrints()
    ClearReplayStats()
    LeaderboardsClearCacheData()
    ClearFocus()
    ClearHdArea()
    ClearPedBloodDamage(PlayerPedId())
    ClearPedWetness(PlayerPedId())
    ClearPedEnvDirt(PlayerPedId())
    ResetPedVisibleDamage(PlayerPedId())
    ClearOverrideWeather()
    DisableVehicleDistantlights(false)
    DisableScreenblurFade()
    SetRainLevel(0.0)
    SetWindSpeed(0.0)
    Citizen.Wait(300)
end)
RegisterNUICallback("button4", function()
    SetTimecycleModifier()
    ClearTimecycleModifier()
    ClearExtraTimecycleModifier()
    Citizen.Wait(300)
end)

function SetDisplay(bool)
    display = bool
    SetNuiFocus(bool, bool)
    SendNUIMessage({
        type = "ui",
        status = bool,
    })
end
